apiVersion: v1
kind: Pod
metadata:
  name: springfield-csi-driver
  labels:
    app: springfield-csi-driver
spec:
  containers:
  - name: springfield-csi-driver
    image: ghcr.io/trgill/springfield-csi-driver:devel
    imagePullPolicy: Always
    securityContext:
      privileged: true
    env:
      - name: CSI_ENDPOINT
        value: unix:///csi/csi.sock
      - name: KUBE_NODE_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
    ports:
    - containerPort: 9898
      name: healthz
      protocol: TCP
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: healthz
      initialDelaySeconds: 10
      timeoutSeconds: 3
      periodSeconds: 2

    volumeMounts:
      - mountPath: /csi
        name: socket-dir
      - mountPath: /var/run/dbus
        mountPropagation: Bidirectional
        name: dbus-socket

  - name: liveness-probe
    volumeMounts:
    - mountPath: /csi
      name: socket-dir
    image: registry.k8s.io/sig-storage/livenessprobe:v2.7.0
    args:
    - --csi-address=/csi/csi.sock
    - --health-port=9898


  volumes:
    - emptyDir: {}
      name: socket-dir
    - hostPath:
        path: /host_dbus
        type: Directory
      name: dbus-socket